name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

    name: Continuous Integration

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none

      - name: Clear cache
        run: rm -rf ~/.composer/cache/*

      - name: Install PHP dependencies
        run: composer update  --no-interaction --no-progress --ansi

      - name: Execute Tests
        run: vendor/bin/pest

